[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ThreeBodyTB = "2a26a249-28ed-4bc9-828d-d3ac47f0d73d"


[compat]
Documenter = "0.25"
Plots = "1"

